<?xml version="1.0" encoding="UTF-8"?>
<project-private xmlns="http://www.netbeans.org/ns/project-private/1">
    <editor-bookmarks xmlns="http://www.netbeans.org/ns/editor-bookmarks/2" lastBookmarkId="0"/>
    <open-files xmlns="http://www.netbeans.org/ns/projectui-open-files/2">
        <group>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/src/java/VerifyClaimServlet.java</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/src/java/com/user/controller/FoundItemServlet.java</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/web/lost_item.jsp</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/web/admin_dashboard.jsp</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/src/java/com/user/controller/RegisterServlet.java</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/src/java/com/user/dao/HandoverDAO.java</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/src/java/com/user/controller/ProfileServlet.java</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/src/java/com/user/controller/HandoverServlet.java</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/web/index.html</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/web/profile.jsp</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/web/claim.jsp</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/src/java/com/user/controller/VerifyServlet.java</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/web/lost_item.html</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/src/java/com/user/dao/UserDAO.java</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/src/java/com/user/model/Report.java</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/web/view_lost.jsp</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/web/verify_notice.jsp</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/src/java/com/user/controller/DashboardServlet.java</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/src/java/com/user/model/Claim.java</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/web/verify.html</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/src/java/com/user/controller/UpdateStatusServlet.java</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/src/java/com/user/model/User.java</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/web/dashboard.jsp</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/web/handover_log.html</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/src/java/com/user/controller/DBConnection.java</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/src/java/com/user/dao/DashboardDAO.java</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/web/manage_notice.jsp</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/src/java/com/user/controller/LogoutServlet.java</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/src/java/com/user/dao/ClaimDAO.java</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/web/verify.jsp</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/web/login.html</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/web/WEB-INF/web.xml</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/src/java/com/user/controller/LoginServlet.java</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/src/java/com/user/controller/LostItemServlet.java</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/web/admin_dashboard.html</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/web/handover_log.jsp</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/web/dashboard.html</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/src/java/com/user/dao/ReportDAO.java</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/src/java/com/user/controller/ViewVerificationServlet.java</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/web/verify_notice.html</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/web/manage_notice.html</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/web/found_item.html</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/web/view_detail.jsp</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/web/found_item.jsp</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/src/java/com/user/controller/ViewReportServlet.java</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/web/claim.html</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/web/verify_action.jsp</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/src/java/com/user/controller/ClaimServlet.java</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/web/login.jsp</file>
            <file>file:/C:/Users/wanrwana/OneDrive%20-%20Universiti%20Teknologi%20MARA/Desktop/csc/LostAndFound/src/java/com/user/model/Handover.java</file>
        </group>
    </open-files>
</project-private>
