CREATE TABLE USER (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    USERNAME VARCHAR(50),
    FULLNAME VARCHAR(100),
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
    ROLE VARCHAR(20),
    PASSWORD VARCHAR(100)
);


CREATE TABLE LOST_ITEMS (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    ITEM_NAME VARCHAR(100),
    LOCATION VARCHAR(100),
    DESCRIPTION VARCHAR(500),
    STATUS VARCHAR(20)
);


CREATE TABLE CLAIM (
    CLAIM_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    ITEM_ID INT,
    USERNAME VARCHAR(50),
    ITEM_NAME VARCHAR(100),
    CLAIM_DATE VARCHAR(20),
    PROOF_DESCRIPTION VARCHAR(500),
    STATUS VARCHAR(20),
    CREATED_AT TIMESTAMP,
    PROOF_IMAGE VARCHAR(255),
    REMARKS VARCHAR(255)
);


CREATE TABLE HANDOVER_LOG (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    CLAIM_ID INT,
    HANDOVER_DATE DATE,
    STATUS VARCHAR(20),
    ITEM_ID INT
);

INSERT INTO USER
(USERNAME,FULLNAME,EMAIL,PHONE,ROLE,PASSWORD)

VALUES
('admin','Admin User','admin@gmail.com','0123456789','admin','12345');