<?xml version="1.0" encoding="UTF-8"?>
<web-app version="3.1" xmlns="http://xmlns.jcp.org/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd">
    <servlet>
        <servlet-name>RegisterServlet</servlet-name>
        <servlet-class>com.user.controller.RegisterServlet</servlet-class>
    </servlet>
    <servlet>
        <servlet-name>LoginServlet</servlet-name>
        <servlet-class>com.user.controller.LoginServlet</servlet-class>
    </servlet>
    <servlet>
        <servlet-name>LostItemServlet</servlet-name>
        <servlet-class>com.user.controller.LostItemServlet</servlet-class>
    </servlet>
    <servlet>
        <servlet-name>FoundItemServlet</servlet-name>
        <servlet-class>com.user.controller.FoundItemServlet</servlet-class>
    </servlet>
    <servlet>
        <servlet-name>Claim</servlet-name>
        <servlet-class>com.user.controller.Claim</servlet-class>
    </servlet>
    <servlet>
        <servlet-name>ClaimServlet</servlet-name>
        <servlet-class>com.user.controller.ClaimServlet</servlet-class>
    </servlet>
    <servlet>
        <servlet-name>VerifyServlet</servlet-name>
        <servlet-class>com.user.controller.VerifyServlet</servlet-class>
    </servlet>
    <servlet>
        <servlet-name>ViewVerificationServlet</servlet-name>
        <servlet-class>com.user.controller.ViewVerificationServlet</servlet-class>
    </servlet>
    <servlet>
        <servlet-name>ViewReportServlet</servlet-name>
        <servlet-class>com.user.controller.ViewReportServlet</servlet-class>
    </servlet>
    <servlet>
        <servlet-name>HandoverServlet</servlet-name>
        <servlet-class>com.user.controller.HandoverServlet</servlet-class>
    </servlet>
    <servlet>
        <servlet-name>UpdateStatusServlet</servlet-name>
        <servlet-class>com.user.controller.UpdateStatusServlet</servlet-class>
    </servlet>
    <servlet>
        <servlet-name>ProfileServlet</servlet-name>
        <servlet-class>com.user.controller.ProfileServlet</servlet-class>
    </servlet>
    <servlet>
        <servlet-name>DashboardServlet</servlet-name>
        <servlet-class>com.user.controller.DashboardServlet</servlet-class>
    </servlet>
    <servlet>
        <servlet-name>LogoutServlet</servlet-name>
        <servlet-class>com.user.controller.LogoutServlet</servlet-class>
    </servlet>
    <servlet>
        <servlet-name>VerifyClaimServlet</servlet-name>
        <servlet-class>VerifyClaimServlet</servlet-class>
    </servlet>
    <servlet>
        <servlet-name>FoundItemsServlet</servlet-name>
        <servlet-class>FoundItemServlet</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>RegisterServlet</servlet-name>
        <url-pattern>/RegisterServlet</url-pattern>
    </servlet-mapping>
    <servlet-mapping>
        <servlet-name>LoginServlet</servlet-name>
        <url-pattern>/LoginServlet</url-pattern>
    </servlet-mapping>
    <servlet-mapping>
        <servlet-name>LostItemServlet</servlet-name>
        <url-pattern>/LostItemServlet</url-pattern>
    </servlet-mapping>
    <servlet-mapping>
        <servlet-name>FoundItemServlet</servlet-name>
        <url-pattern>/FoundItemServlet</url-pattern>
    </servlet-mapping>
    <servlet-mapping>
        <servlet-name>Claim</servlet-name>
        <url-pattern>/Claim</url-pattern>
    </servlet-mapping>
    <servlet-mapping>
        <servlet-name>ClaimServlet</servlet-name>
        <url-pattern>/ClaimServlet</url-pattern>
    </servlet-mapping>
    <servlet-mapping>
        <servlet-name>VerifyServlet</servlet-name>
        <url-pattern>/VerifyServlet</url-pattern>
    </servlet-mapping>
    <servlet-mapping>
        <servlet-name>ViewVerificationServlet</servlet-name>
        <url-pattern>/ViewVerificationServlet</url-pattern>
    </servlet-mapping>
    <servlet-mapping>
        <servlet-name>ViewReportServlet</servlet-name>
        <url-pattern>/ViewReportServlet</url-pattern>
    </servlet-mapping>
    <servlet-mapping>
        <servlet-name>HandoverServlet</servlet-name>
        <url-pattern>/HandoverServlet</url-pattern>
    </servlet-mapping>
    <servlet-mapping>
        <servlet-name>UpdateStatusServlet</servlet-name>
        <url-pattern>/UpdateStatusServlet</url-pattern>
    </servlet-mapping>
    <servlet-mapping>
        <servlet-name>ProfileServlet</servlet-name>
        <url-pattern>/ProfileServlet</url-pattern>
    </servlet-mapping>
    <servlet-mapping>
        <servlet-name>DashboardServlet</servlet-name>
        <url-pattern>/DashboardServlet</url-pattern>
    </servlet-mapping>
    <servlet-mapping>
        <servlet-name>LogoutServlet</servlet-name>
        <url-pattern>/LogoutServlet</url-pattern>
    </servlet-mapping>
    <servlet-mapping>
        <servlet-name>VerifyClaimServlet</servlet-name>
        <url-pattern>/VerifyClaimServlet</url-pattern>
    </servlet-mapping>
    <servlet-mapping>
        <servlet-name>FoundItemsServlet</servlet-name>
        <url-pattern>/FoundItemsServlet</url-pattern>
    </servlet-mapping>
    <session-config>
        <session-timeout>
            30
        </session-timeout>
    </session-config>
</web-app>
